import { contextBridge, ipcRenderer } from 'electron';
import type { FormaApi } from '../shared/contracts';
const api: FormaApi = {
  mcpStatus:()=>ipcRenderer.invoke('mcp-status'),
  mcpConnect:()=>ipcRenderer.invoke('mcp-connect'),
  mcpCancel:()=>ipcRenderer.invoke('mcp-cancel'),
  mcpDisconnect:()=>ipcRenderer.invoke('mcp-disconnect'),
  setSkillEnabled:input=>ipcRenderer.invoke('set-skill-enabled',input),
  discoverTools:()=>ipcRenderer.invoke('discover-tools'),
  setLocale:locale=>ipcRenderer.invoke('set-locale',locale),
  pickConversationWorkspace:()=>ipcRenderer.invoke('pick-conversation-workspace'),
  openSettings:()=>ipcRenderer.invoke('open-settings'),
  onTaskProgress:listener=>{const handler=(_event:Electron.IpcRendererEvent,progress:Parameters<typeof listener>[0])=>listener(progress);ipcRenderer.on('task-progress',handler);return ()=>ipcRenderer.removeListener('task-progress',handler);},
  createConversation:input=>ipcRenderer.invoke('create-conversation',input),
  sidebarAction:input=>ipcRenderer.invoke('sidebar-action',input),
  deleteConversation:id=>ipcRenderer.invoke('delete-conversation',id),
  selectConversation:id=>ipcRenderer.invoke('select-conversation',id),
  updateConversation:input=>ipcRenderer.invoke('update-conversation',input),
  saveLayout:input=>ipcRenderer.invoke('save-layout',input),
  browserBounds:input=>ipcRenderer.invoke('browser-bounds',input),
  browserControl:input=>ipcRenderer.invoke('browser-control',input),
  copySource:input=>ipcRenderer.invoke('copy-source',input),
  previewRelated:input=>ipcRenderer.invoke('preview-related',input),
  preview:input=>ipcRenderer.invoke('preview',input),
  state: () => ipcRenderer.invoke('state'),
  saveModel: input => ipcRenderer.invoke('save-model', input),
  deleteModel: () => ipcRenderer.invoke('delete-model'),
  chooseWorkspace: () => ipcRenderer.invoke('choose-workspace'),
  runTask:(prompt,member)=>ipcRenderer.invoke('run-task',{prompt,member}),
  stopTask:()=>ipcRenderer.invoke('stop-task'),
  forgetWorkspace:()=>ipcRenderer.invoke('forget-workspace'),
  roleRequests:()=>ipcRenderer.invoke('role-requests'),
  resolveRoleRequest:input=>ipcRenderer.invoke('resolve-role-request',input),
  handoffRules:()=>ipcRenderer.invoke('handoff-rules'),
  deleteHandoffRule:rule=>ipcRenderer.invoke('delete-handoff-rule',rule),
  approvalRules:()=>ipcRenderer.invoke('approval-rules'),
  createTeamFromDocument:()=>ipcRenderer.invoke('create-team-from-document'),
  browserPick:()=>ipcRenderer.invoke('browser-pick'),
  browserCapture:()=>ipcRenderer.invoke('browser-capture'),
  pasteImage:input=>ipcRenderer.invoke('paste-image',input),
  attachmentImage:(input:{id:string})=>ipcRenderer.invoke('attachment-image',input),
  removeAttachment:(input:{id:string})=>ipcRenderer.invoke('remove-attachment',input),
  setOutputDir:(dir:string)=>ipcRenderer.invoke('set-output-dir',dir),
  setMemberModel:(input:{botId:string;provider:string;model:string|null})=>ipcRenderer.invoke('set-member-model',input),
  memories:()=>ipcRenderer.invoke('memories'),
  deleteMemory:(input:{id:number})=>ipcRenderer.invoke('delete-memory',input),
  deleteApprovalRule:rule=>ipcRenderer.invoke('delete-approval-rule',rule),
};
contextBridge.exposeInMainWorld('forma', api);
