import {_electron as electron} from 'playwright-core';
import {mkdtemp,mkdir,readFile,writeFile,copyFile} from 'node:fs/promises';
import {resolve,join} from 'node:path';import {build} from 'esbuild';import {pathToFileURL} from 'node:url';import assert from 'node:assert/strict';
const dir=await mkdtemp(resolve('.tmp/live-e05a-')),workspace=`${dir}-workspace`;await mkdir(workspace);
const production=join(process.env.HOME,'Library/Application Support/formabot');const config=JSON.parse(await readFile(join(production,'settings.json'),'utf8'));if(!config.model?.secret)throw Error('没有已配置的真实模型');config.workspace={path:workspace,authorized:false};await writeFile(join(dir,'settings.json'),JSON.stringify(config),{mode:0o600});await copyFile(join(production,'Local State'),join(dir,'Local State'));
const moduleFile=join(dir,'store.mjs');await build({entryPoints:['src/state/workbench.ts'],outfile:moduleFile,bundle:true,platform:'node',format:'esm'});const {WorkbenchStore}=await import(pathToFileURL(moduleFile).href);const store=new WorkbenchStore(join(dir,'workbench.sqlite'));
const id=store.create(workspace,{name:'素材编辑',role:'你是内容编辑，负责将用户给定素材改写为短视频口播稿；不负责数据复盘。不得编造数据或来源。',kind:'bot',members:[]});const peer=store.create(workspace,{name:'资料核验员',role:'只核验用户提供的事实来源。',kind:'bot',members:[]});const group=store.create(workspace,{name:'身份验收组',role:'各自在职责内处理素材。',kind:'group',members:[id,peer]});store.select(workspace,id);store.close();
const sameMaterial='材料：每天用十分钟整理书桌，可以减少找东西的时间。两条试播视频的数据为：A播放1000、完播400，B播放2000、完播600。请根据你自己的岗位，只做职责内的一项工作并直接给出结果。只代表你自己回复，不写文件、不联网、不分工。';
const env={...process.env,FORMABOT_TEST_DATA_DIR:dir};delete env.ELECTRON_RUN_AS_NODE;let app,page;const evidence=[];
async function launch(){app=await electron.launch({executablePath:resolve(process.env.FORMABOT_TEST_APP||'build/e05a/mac-arm64/FormaBot.app/Contents/MacOS/FormaBot'),env,timeout:30000});page=await app.firstWindow();await page.locator('#workbench').waitFor();await page.waitForFunction(()=>!document.querySelector('#run').disabled);await app.evaluate(({dialog})=>{globalThis.identityPermissions=0;dialog.showMessageBox=async()=>{globalThis.identityPermissions++;return {response:0,checkboxChecked:false};};});}
async function state(){const r=await page.evaluate(()=>window.forma.state());assert.ok(r.ok);return r.value;}
async function run(text,version){console.log(`Running real task with role v${version}`);await page.locator('#task').fill(text);await page.locator('#run').click();const deadline=Date.now()+180000;let s;while(Date.now()<deadline){s=await state();if(s.task&&s.task.status!=='running')break;await new Promise(r=>setTimeout(r,200));}assert.ok(['completed','responded'].includes(s.task?.status),s.jobs.find(j=>j.id===s.task?.jobId)?.error||s.task?.output||s.task?.status);const job=s.jobs.find(j=>j.id===s.task.jobId);assert.equal(job.member,id);assert.equal(job.roleVersion,version);const message=s.messages.filter(m=>m.taskId===job.id&&m.authorKind==='bot').at(-1);assert.equal(message.authorId,id);assert.equal(message.roleVersion,version);assert.ok(message.content.length>5);evidence.push({conversation:s.selected,job,reply:message,model:s.model.model});return s;}
try{
 await launch();let s=await run(sameMaterial,1);assert.match(s.messages.at(-1).content,/书桌|整理/);assert.doesNotMatch(s.messages.at(-1).content,/完播率[：:]/);const historical=s.messages.find(m=>m.authorKind==='bot');
 await page.waitForFunction(id=>!!document.querySelector(`#messages .identity-avatar[data-member-id="${id}"]`),id);const oldAvatar=await page.locator(`#messages .identity-avatar[data-member-id="${id}"]`).first().innerHTML();
 await page.locator('#conversation-title').click();await page.locator('#bot-name').fill('数据复盘师');await page.locator('#bot-role').fill('你是数据复盘师，职责是分析用户给定的播放、完播与互动数据，计算指标并提出有依据的优化建议。你不再是内容编辑，不负责口播写作；不编造缺失的数据或来源。');await page.locator('#conversation-form button[type=submit]').click();await page.waitForFunction(()=>!document.querySelector('#conversation-dialog').open);
 s=await state();assert.equal(s.selected,id);assert.equal(s.roleHistory.length,2);assert.equal(s.roleHistory[0].version,2);assert.deepEqual(s.messages.find(m=>m.id===historical.id),historical);await page.waitForTimeout(750);assert.equal(await page.locator(`#messages .identity-avatar[data-member-id="${id}"]`).first().innerHTML(),oldAvatar);
 await page.locator('#conversation-title').click();await page.locator('#role-history summary').click();assert.match(await page.locator('#role-history').textContent(),/版本 2/);await page.screenshot({path:join(dir,'role-history.png')});await page.locator('#dialog-cancel').click();
 const selected=await page.evaluate(group=>window.forma.selectConversation(group),group);assert.ok(selected.ok);await page.waitForFunction(()=>document.querySelector('#conversation-title')?.textContent==='身份验收组').catch(async()=>{await page.waitForTimeout(800);});
 s=await run('@数据复盘师 '+sameMaterial,2);assert.match(s.messages.at(-1).content,/40\s*%/);assert.match(s.messages.at(-1).content,/30\s*%/);assert.equal(s.jobs.filter(j=>j.member===peer).length,0);assert.equal(await app.evaluate(()=>globalThis.identityPermissions),1);
 await app.close();app=undefined;await launch();s=await state();assert.equal(s.workspace.path,workspace);assert.equal(s.workspace.authorized,true);assert.ok(s.model.hasKey);assert.equal(s.conversations.find(c=>c.id===id).roleVersion,2);
 await page.evaluate(id=>window.forma.selectConversation(id),id);await page.waitForTimeout(800);s=await run('材料：视频C播放500，完播250。请根据你自己的岗位给出一项工作结果。直接在聊天回复，不写文件、不联网、不分工。',2);assert.match(s.messages.at(-1).content,/50\s*%/);assert.equal(await app.evaluate(()=>globalThis.identityPermissions),0);assert.ok(s.messages.some(m=>m.id===historical.id&&m.authorId===id&&m.speaker==='素材编辑'));
 await page.screenshot({path:join(dir,'restarted-private.png')});await writeFile(join(dir,'evidence.json'),JSON.stringify({model:s.model.model,workspace,botId:id,evidence},null,2));console.log(`PASS real model ${s.model.model}: private v1, group v2, restart private v2, permanent authors, same avatar, role history, saved model/workspace and one-time authorization. Evidence ${dir}`);
}finally{await app?.close();}
